# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb3d7a612b07952988be4e0c4ffe88ea20f6b38ce251c3c87a0e2159d11d344c6894a211692dd972a14836eee2689ef91cba78fbd77cb46ffb20be0d8d514d7c

test:
  secret_key_base: 61e364df56831b1baf843ecd490c2b0c56b1410704b01be5dd20fa730008dd75d35c6fcfd553ecd7bc89953dc49c97c1409946ac15468b0b6e1a3cc8cdfbb5c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
